[package]
name = "emu_openmm"
version = "0.1.0"
authors = ["Caleb Winston <calebhwin@gmail.com>"]
edition = "2018"

[dependencies]
emu_glsl = { path = "../emu_glsl" }
futures = "0.3.4"
zerocopy = "0.2.8"
lazy_static = "1.4.0"

[dependencies.emu_core]
path = "../emu_core"
default-features = false
features = ["glsl-compile"]

[lib]
crate-type = ["staticlib"] # this ensure that we generate a static library, more details here: https://doc.rust-lang.org/reference/linkage.html